<a href="https://colab.research.google.com/github/SWtheWhite/DLbasic/blob/main/01_Pytorch_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pytorch 임포트

In [ ]:
import torch

# 텐서 생성

In [ ]:
# 정수형
lt = torch.LongTensor([[1,2],
                       [3,4]])
print(lt)

tensor([[1, 2],
        [3, 4]])


In [ ]:
# 실수형
ft = torch.FloatTensor([[1,2],
                        [3,4]])
print(ft)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
# Byte(2진수)
bt = torch.ByteTensor([[1,0],
                       [0,1]])
print(bt)

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)


In [ ]:
# 번외 - 텐서 크기만 지정해서 생성
rdm = torch.FloatTensor(3,2)
print(rdm)

tensor([[-1.9736e-33,  3.0922e-41],
        [ 5.0447e-44,  0.0000e+00],
        [        nan,  0.0000e+00]])


#Numpy와의 호환

In [ ]:
import numpy as np

# Numpy 배열 생성
x = np.array([[1, 2],
              [3, 4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [ ]:
# 텐서로 변환
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [ ]:
# Numpy로 변환
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


#텐서의 타입 변환

In [ ]:
# 정수로 변환
ft.long()

tensor([[1, 2],
        [3, 4]])

In [ ]:
# 실수로 변환
lt.float()

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
# byte로 변환
torch.FloatTensor([1,0]).byte()

tensor([1, 0], dtype=torch.uint8)

#텐서의 Shape

In [ ]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

In [ ]:
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [ ]:
print(x.dim())
print(len(x.size()))

3
3


In [ ]:
print(x.size(1))
print(x.shape[1])

2
2


In [ ]:
print(x.size(-1))
print(x.shape[-1])

2
2
