<a href="https://colab.research.google.com/github/SWtheWhite/DLbasic/blob/main/02_Pytorch_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

#사칙연산

In [ ]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[2, 2],
                       [3, 3]])

In [ ]:
# 더하기
a + b

tensor([[3., 4.],
        [6., 7.]])

In [ ]:
# 빼기
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [ ]:
# 곱하기
a * b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [ ]:
# 나누기
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [ ]:
# 동일 유무
a == b

tensor([[False,  True],
        [ True, False]])

In [ ]:
# 불일치 유무
a != b

tensor([[ True, False],
        [False,  True]])

In [ ]:
# 제곱하기
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

# 두가지 곱 (기존데이터 활용에 따라)

In [ ]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
# 기존 데이터 변형 X
print(a.mul(b))
print(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])


In [ ]:
# 기존 데이터 변형 O
print(a.mul_(b))
print(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


# 합과 평균

In [ ]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

In [ ]:
# 합
print(x.sum())
# 평균
print(x.mean())

tensor(10.)
tensor(2.5000)


In [ ]:
# 차원0의 합 ↓
print(x.sum(dim=0))
# 차원-1의 합 →
print(x.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])


# 브로드캐스트

In [3]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([1, 2])


In [4]:
z = x + y
print(z)
print(z.size())

tensor([[ 5., 10.]])
torch.Size([1, 2])


## 텐서+스칼라

In [5]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = 1

print(x.size())

torch.Size([2, 2])


In [7]:
z = x + y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


## 텐서+벡터

In [21]:
x = torch.FloatTensor([[1, 2],
                       [4, 8]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([2, 2])
torch.Size([2])


In [22]:
# y size 브로드캐스팅 (2,) => (1,2)
z = x + y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [19]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [20]:
# y size 브로드캐스팅 (2,) => (1,1,2)
z = x + y
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


## 텐서+텐서

In [16]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [17]:
# x size 브로드캐스팅 (1,2) => (2,2)
# y size 브로드캐스팅 (2,1) => (2,2)
z = x + y

print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


## 에러 케이스

In [15]:
x = torch.FloatTensor([[[1, 2],
                        [4, 8]]])
y = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(x.size())
print(y.size())

# 브로드캐스팅이 안되는 경우
z = x + y

torch.Size([1, 2, 2])
torch.Size([3, 3])


RuntimeError: ignored