<a href="https://colab.research.google.com/github/SWtheWhite/DLbasic/blob/main/03_Pytorch_%ED%85%90%EC%84%9C_%EC%A1%B0%EC%9E%91.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# 텐서 모양 조작

## reshape

텐서 모양 바꾸기

In [2]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

print(x.size())

torch.Size([3, 2, 2])


In [3]:
print(x.reshape(12)) # 12 = 3 * 2 * 2
print(x.reshape(-1))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [4]:
print(x.reshape(3, 4)) # 3 * 4 = 3 * 2 * 2
print(x.reshape(3, -1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [6]:
print(x.reshape(3, 1, 4))
print(x.reshape(-1, 1, 4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [7]:
print(x.reshape(3, 2, 2, 1))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


특정 케이스에선 'view()'를 'reshape()' 대신에 사용할 수 있다.

- https://pytorch.org/docs/stable/tensor_view.html
- https://pytorch.org/docs/stable/tensors.html?highlight=view#torch.Tensor.view

## squeeze

차원의 사이즈가 1인, 특정 차원을 제거

In [8]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])
print(x.size())

torch.Size([1, 2, 2])


In [9]:
# Squeeze
print(x.squeeze())
print(x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [12]:
# 특정 차원을 제거 가능한데, 차원의 사이즈가 1이여야 한다는 조건이 있다
# 그렇지 않다면 변화는 없다

print(x.squeeze(0).size())
print(x.squeeze(1).size())

torch.Size([2, 2])
torch.Size([1, 2, 2])


## unsqueeze

특정 인덱스에 차원 추가

In [14]:
x = torch.FloatTensor([[1, 2],
                        [3, 4]])
print(x.size())

torch.Size([2, 2])


In [15]:
print(x.unsqueeze(2))
print(x.unsqueeze(-1))
print(x.reshape(2, 2, -1))

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
