<a href="https://colab.research.google.com/github/SWtheWhite/DLbasic/blob/main/Pytorch_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch 임포트

In [1]:
import torch

텐서 생성

In [8]:
lt = torch.LongTensor([[1,2],
                       [3,4]]) # 정수형
print(lt)

tensor([[1, 2],
        [3, 4]])


In [9]:
ft = torch.FloatTensor([[1,2],
                        [3,4]]) # 실수형
print(ft)

tensor([[1., 2.],
        [3., 4.]])


In [7]:
bt = torch.ByteTensor([[1,0],
                       [0,1]]) # Byte(2진수)
print(bt)

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)


In [10]:
# 번외 - 텐서 크기만 지정해서 생성
rdm = torch.FloatTensor(3,2)
print(rdm)

tensor([[4.9906e+23, 3.0920e-41],
        [3.3631e-44, 0.0000e+00],
        [       nan, 1.5554e-43]])


Numpy와의 호환

In [11]:
import numpy as np

# Numpy 배열 생성
x = np.array([[1, 2],
              [3, 4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [12]:
# 텐서로 변환
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [13]:
# Numpy로 변환
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


텐서의 타입 변환

In [14]:
# 정수로 변환
ft.long()

tensor([[1, 2],
        [3, 4]])

In [15]:
# 실수로 변환
lt.float()

tensor([[1., 2.],
        [3., 4.]])

In [16]:
# byte로 변환
torch.FloatTensor([1,0]).byte()

tensor([1, 0], dtype=torch.uint8)